title: bulkfilepr
description: "Batch-update one or more standardized files across many local GitHub repositories, then commit the changes on a new branch and open pull requests back to each repositoryâ€™s default branch."

remote_theme: just-the-docs/just-the-docs@v0.12.0
plugins:
  - jekyll-remote-theme

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "11.12.3"

# External navigation links
nav_external_links:
  - title: bulkfilepr on GitHub
    url: https://github.com/UnitVectorY-Labs/bulkfilepr

# Footer "Edit this page on GitHub" link text
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/UnitVectorY-Labs/bulkfilepr"
gh_edit_branch: "main"
gh_edit_source: "docs"
gh_edit_view_mode: "tree"
